
export const data = [
  {
    strMeal: "Brown Stew Chicken",
    img: "https://www.themealdb.com/images/media/meals/sypxpx1515365095.jpg",
    idMeal: "52940",
    category: "chicken",
  },

  {
    strMeal: "Chicken & mushroom Hotpot",
    img: "https://www.themealdb.com/images/media/meals/uuuspp1511297945.jpg",
    idMeal: "52846",
    category: "chicken",
  },
  {
    strMeal: "Chicken Alfredo Primavera",
    img: "https://www.themealdb.com/images/media/meals/syqypv1486981727.jpg",
    idMeal: "52796",
    category: "chicken",
  },
  {
    strMeal: "Chicken Basquaise",
    img: "https://www.themealdb.com/images/media/meals/wruvqv1511880994.jpg",
    idMeal: "52934",
    category: "chicken",
  },
  {
    strMeal: "Chicken Congee",
    img: "https://www.themealdb.com/images/media/meals/1529446352.jpg",
    idMeal: "52956",
    category: "chicken",
  },
  {
    strMeal: "Chicken Handi",
    img: "https://www.themealdb.com/images/media/meals/wyxwsp1486979827.jpg",
    idMeal: "52795",
    category: "chicken",
  },
  {
    strMeal: "Kentucky Fried Chicken",
    img: "https://www.themealdb.com/images/media/meals/xqusqy1487348868.jpg",
    idMeal: "52813",
    category: "chicken",
  },
  {
    strMeal: "Kung Pao Chicken",
    img: "https://www.themealdb.com/images/media/meals/1525872624.jpg",
    idMeal: "52945",
    category: "chicken",
  },
  {
    strMeal: "Pad See Ew",
    img: "https://www.themealdb.com/images/media/meals/uuuspp1468263334.jpg",
    idMeal: "52774",
    category: "chicken",
  },
  {
    strMeal: "Piri-piri chicken and slaw",
    img: "https://www.themealdb.com/images/media/meals/hglsbl1614346998.jpg",
    idMeal: "53039",
    category: "chicken",
  },
  {
    strMeal: "Thai Green Curry",
    img: "https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg",
    idMeal: "52814",
    category: "chicken",
  },

  {
    strMeal: "Beef and Mustard Pie",
    img: "https://www.themealdb.com/images/media/meals/sytuqu1511553755.jpg",
    idMeal: "52874",
    category: "beef",
  },
  {
    strMeal: "Beef and Oyster pie",
    img: "https://www.themealdb.com/images/media/meals/wrssvt1511556563.jpg",
    idMeal: "52878",
    category: "beef",
  },
  {
    strMeal: "Beef Asado",
    img: "https://www.themealdb.com/images/media/meals/pkopc31683207947.jpg",
    idMeal: "53071",
    category: "beef",
  },
  {
    strMeal: "Beef Caldereta",
    img: "https://www.themealdb.com/images/media/meals/41cxjh1683207682.jpg",
    idMeal: "53070",
    category: "beef",
  },
  {
    strMeal: "Beef Dumpling Stew",
    img: "https://www.themealdb.com/images/media/meals/uyqrrv1511553350.jpg",
    idMeal: "52873",
    category: "beef",
  },
  {
    strMeal: "Beef Lo Mein",
    img: "https://www.themealdb.com/images/media/meals/1529444830.jpg",
    idMeal: "52952",
    category: "beef",
  },
  {
    strMeal: "Beef Mechado",
    img: "https://www.themealdb.com/images/media/meals/cgl60b1683206581.jpg",
    idMeal: "53068",
    category: "beef",
  },
  {
    strMeal: "Beef Rendang",
    img: "https://www.themealdb.com/images/media/meals/bc8v651619789840.jpg",
    idMeal: "53053",
    category: "beef",
  },
  {
    strMeal: "Beef Sunday Roast",
    img: "https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg",
    idMeal: "52824",
    category: "beef",
  },
  {
    strMeal: "Bistek",
    img: "https://www.themealdb.com/images/media/meals/4pqimk1683207418.jpg",
    idMeal: "53069",
    category: "beef",
  },
  {
    strMeal: "Bitterballen (Dutch meatballs)",
    img: "https://www.themealdb.com/images/media/meals/lhqev81565090111.jpg",
    idMeal: "52979",
    category: "beef",
  },
  {
    strMeal: "Braised Beef Chilli",
    img: "https://www.themealdb.com/images/media/meals/uuqvwu1504629254.jpg",
    idMeal: "52826",
    category: "beef",
  },
  {
    strMeal: "Egyptian Fatteh",
    img: "https://www.themealdb.com/images/media/meals/rlwcc51598734603.jpg",
    idMeal: "53031",
    category: "beef",
  },
  {
    strMeal: "Massaman Beef curry",
    img: "https://www.themealdb.com/images/media/meals/tvttqv1504640475.jpg",
    idMeal: "52827",
    category: "beef",
  },
  {
    strMeal: "Moussaka",
    img: "https://www.themealdb.com/images/media/meals/ctg8jd1585563097.jpg",
    idMeal: "53006",
    category: "beef",
  },
  {
    strMeal: "Mulukhiyah",
    img: "https://www.themealdb.com/images/media/meals/x372ug1598733932.jpg",
    idMeal: "53029",
    category: "beef",
  },
  {
    strMeal: "Red Peas Soup",
    img: "https://www.themealdb.com/images/media/meals/sqpqtp1515365614.jpg",
    idMeal: "52941",
    category: "beef",
  },
  {
    strMeal: "Steak and Kidney Pie",
    img: "https://www.themealdb.com/images/media/meals/qysyss1511558054.jpg",
    idMeal: "52881",
    category: "beef",
  },
  {
    strMeal: "Szechuan Beef",
    img: "https://www.themealdb.com/images/media/meals/1529443236.jpg",
    idMeal: "52950",
    category: "beef",
  },
  {
    strMeal: "Traditional Croatian Goulash",
    img: "https://www.themealdb.com/images/media/meals/n1hcou1628770088.jpg",
    idMeal: "53057",
    category: "beef",
  },

  {
    strMeal: "Baked salmon with fennel & tomatoes",
    img: "https://www.themealdb.com/images/media/meals/1548772327.jpg",
    idMeal: "52959",
    category: "Seafood",
  },
  {
    strMeal: "Cajun spiced fish tacos",
    img: "https://www.themealdb.com/images/media/meals/uvuyxu1503067369.jpg",
    idMeal: "52819",
    category: "Seafood",
  },
  {
    strMeal: "Escovitch Fish",
    img: "https://www.themealdb.com/images/media/meals/1520084413.jpg",
    idMeal: "52944",
    category: "Seafood",
  },
  {
    strMeal: "Fish fofos",
    img: "https://www.themealdb.com/images/media/meals/a15wsa1614349126.jpg",
    idMeal: "53043",
    category: "Seafood",
  },
  {
    strMeal: "Fish pie",
    img: "https://www.themealdb.com/images/media/meals/ysxwuq1487323065.jpg",
    idMeal: "52802",
    category: "Seafood",
  },
  {
    strMeal: "Fish Stew with Rouille",
    img: "https://www.themealdb.com/images/media/meals/vptqpw1511798500.jpg",
    idMeal: "52918",
    category: "Seafood",
  },
  {
    strMeal: "Garides Saganaki",
    img: "https://www.themealdb.com/images/media/meals/wuvryu1468232995.jpg",
    idMeal: "52764",
    category: "Seafood",
  },
  {
    strMeal: "Grilled Portuguese sardines",
    img: "https://www.themealdb.com/images/media/meals/lpd4wy1614347943.jpg",
    idMeal: "53041",
    category: "Seafood",
  },
  {
    strMeal: "Honey Teriyaki Salmon",
    img: "https://www.themealdb.com/images/media/meals/xxyupu1468262513.jpg",
    idMeal: "52773",
    category: "Seafood",
  },
  {
    strMeal: "Kedgeree",
    img: "https://www.themealdb.com/images/media/meals/utxqpt1511639216.jpg",
    idMeal: "52887",
    category: "Seafood",
  },
  {
    strMeal: "Kung Po Prawns",
    img: "https://www.themealdb.com/images/media/meals/1525873040.jpg",
    idMeal: "52946",
    category: "Seafood",
  },
  {
    strMeal: "Laksa King Prawn Noodles",
    img: "https://www.themealdb.com/images/media/meals/rvypwy1503069308.jpg",
    idMeal: "52821",
    category: "Seafood",
  },
  {
    strMeal: "Mediterranean Pasta Salad",
    img: "https://www.themealdb.com/images/media/meals/wvqpwt1468339226.jpg",
    idMeal: "52777",
    category: "Seafood",
  },
  {
    strMeal: "Mee goreng mamak",
    img: "https://www.themealdb.com/images/media/meals/xquakq1619787532.jpg",
    idMeal: "53048",
    category: "Seafood",
  },
  {
    strMeal: "Nasi lemak",
    img: "https://www.themealdb.com/images/media/meals/wai9bw1619788844.jpg",
    idMeal: "53051",
    category: "Seafood",
  },
  {
    strMeal: "Portuguese fish stew (Caldeirada de peixe)",
    img: "https://www.themealdb.com/images/media/meals/do7zps1614349775.jpg",
    idMeal: "53045",
    category: "Seafood",
  },
  {
    strMeal: "Recheado Masala Fish",
    img: "https://www.themealdb.com/images/media/meals/uwxusv1487344500.jpg",
    idMeal: "52809",
    category: "Seafood",
  },
  {
    strMeal: "Salmon Avocado Salad",
    img: "https://www.themealdb.com/images/media/meals/1549542994.jpg",
    idMeal: "52960",
    category: "Seafood",
  },
  {
    strMeal: "Salmon Prawn Risotto",
    img: "https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg",
    idMeal: "52823",
    category: "Seafood",
  },
  {
    strMeal: "Saltfish and Ackee",
    img: "https://www.themealdb.com/images/media/meals/vytypy1511883765.jpg",
    idMeal: "52936",
    category: "Seafood",
  },
  {
    strMeal: "Seafood fideu\u00e0",
    img: "https://www.themealdb.com/images/media/meals/wqqvyq1511179730.jpg",
    idMeal: "52836",
    category: "Seafood",
  },
  {
    strMeal: "Shrimp Chow Fun",
    img: "https://www.themealdb.com/images/media/meals/1529445434.jpg",
    idMeal: "52953",
    category: "Seafood",
  },
  {
    strMeal: "Sledz w Oleju (Polish Herrings)",
    img: "https://www.themealdb.com/images/media/meals/7ttta31593350374.jpg",
    idMeal: "53023",
    category: "Seafood",
  },
  {
    strMeal: "Spring onion and prawn empanadas",
    img: "https://www.themealdb.com/images/media/meals/1c5oso1614347493.jpg",
    idMeal: "53040",
    category: "Seafood",
  },
  {
    strMeal: "Sushi",
    img: "https://www.themealdb.com/images/media/meals/g046bb1663960946.jpg",
    idMeal: "53065",
    category: "Seafood",
  },
  {
    strMeal: "Three Fish Pie",
    img: "https://www.themealdb.com/images/media/meals/spswqs1511558697.jpg",
    idMeal: "52882",
    category: "Seafood",
  },
  {
    strMeal: "Tuna and Egg Briks",
    img: "https://www.themealdb.com/images/media/meals/2dsltq1560461468.jpg",
    idMeal: "52975",
    category: "Seafood",
  },
  {
    strMeal: "Tuna Nicoise",
    img: "https://www.themealdb.com/images/media/meals/yypwwq1511304979.jpg",
    idMeal: "52852",
    category: "Seafood",
  },

  {
    strMeal: "Breakfast Potatoes",
    img: "https://www.themealdb.com/images/media/meals/1550441882.jpg",
    idMeal: "52965",
    category: "breakfast",
  },
  {
    strMeal: "English Breakfast",
    img: "https://www.themealdb.com/images/media/meals/utxryw1511721587.jpg",
    idMeal: "52895",
    category: "breakfast",
  },
  {
    strMeal: "Fruit and Cream Cheese Breakfast Pastries",
    img: "https://www.themealdb.com/images/media/meals/1543774956.jpg",
    idMeal: "52957",
    category: "breakfast",
  },
  {
    strMeal: "Full English Breakfast",
    img: "https://www.themealdb.com/images/media/meals/sqrtwu1511721265.jpg",
    idMeal: "52896",
    category: "breakfast",
  },
  {
    strMeal: "Home-made Mandazi",
    img: "https://www.themealdb.com/images/media/meals/thazgm1555350962.jpg",
    idMeal: "52967",
    category: "breakfast",
  },
  {
    strMeal: "Salmon Eggs Eggs Benedict",
    img: "https://www.themealdb.com/images/media/meals/1550440197.jpg",
    idMeal: "52962",
    category: "breakfast",
  },
  {
    strMeal: "Smoked Haddock Kedgeree",
    img: "https://www.themealdb.com/images/media/meals/1550441275.jpg",
    idMeal: "52964",
    category: "breakfast",
  },
];
